### PR TITLE
Added pebble-rtltr to support RTL languages and elbbeP firmware

### PR DESCRIPTION
**Pull request by flocsy**

### CODE REVIEW

**Comment by matejdro** [comment]
Did you test this on classic Pebbles? Apps is very near memory ceiling, so adding anything could cause it to not work on classic watches.

Also, why image changes?

**Comment by flocsy** [comment]
image wasn't changed, just "chmod -x" (for some reason they were executables)

as for testing: I only have a Pebble Time, the rest I can only test in emulator, but not sure how I can do that since I need to "receive a call" and the phone has to send a name in Hebrew.

**Comment by matejdro** [comment]
That is a bit problematic. Could you post pbw to somewhere in the Google+ Group?

**Comment by matejdro** [comment]
I took a look at your rtl library and it looks like a lot of code. I'm almost completely sure it won't work on classic Pebbles.

If you can't test, can you just play it safe and wrap all RTL stuff into `#ifndef PBL_LOW_MEMORY`? Otherwise call regular methods on classic Pebbles.

**Comment by flocsy** [comment]
OK I added that

**Comment by matejdro** [comment]
Merged, thanks for the contribution!

**Pull request merged**
